### ISSUE TITLE
error when clicking on "already registered? login here!" button

### ISSUE THREAD

**Issue by fabricio1099** [fabricio1099/mynotes#5]
logs:
`E/flutter ( 3934): #2      Bloc.on.<anonymous closure>.handleEvent
package:bloc/src/bloc.dart:226
E/flutter ( 3934): #3      Bloc.on.<anonymous closure>
package:bloc/src/bloc.dart:235
E/flutter ( 3934): #4      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
E/flutter ( 3934): #5      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 3934): #6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 3934): #7      CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
E/flutter ( 3934): #8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 3934): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 3934): #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 3934): #11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 3934): #12     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter ( 3934): #13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 3934): #14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
`

**Comment by fabricio1099** [comment]
fixed.
added loggedIn variable in AuthState to effectively know when the user is logged in.
