### ISSUE TITLE
error when clicking on "back to login" button on forgot password screen

### ISSUE THREAD

**Issue by fabricio1099** [fabricio1099/mynotes#6]
logs:
`E/flutter ( 4235): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'UserNotLoggedInAuthException'
E/flutter ( 4235): #0      FirebaseAuthProvider.logOut
package:mynotes/…/auth/firebase_auth_provider.dart:115
E/flutter ( 4235): #1      new AuthBloc.<anonymous closure>
package:mynotes/…/bloc/auth_bloc.dart:104
E/flutter ( 4235): #2      Bloc.on.<anonymous closure>.handleEvent
package:bloc/src/bloc.dart:226
E/flutter ( 4235): #3      Bloc.on.<anonymous closure>
package:bloc/src/bloc.dart:235
E/flutter ( 4235): #4      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
E/flutter ( 4235): #5      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 4235): #6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 4235): #7      CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
E/flutter ( 4235): #8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 4235): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 4235): #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4235): #11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 4235): #12     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter ( 4235): #13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 4235): #14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 4235): #15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 4235): #16     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter ( 4235): #17     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter ( 4235): #18     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter ( 4235): #19     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 4235): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)`

**Comment by fabricio1099** [comment]
fixed.
added loggedIn variable in AuthState to effectively know when the user is logged in.
